services:
  frontend-root:
    image: ghcr.io/tart-telescope/web_app/viewer-root:${CI_COMMIT_SHA}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_PROJECT_NAME: viewer
        BASE_URL: ""
        CI_COMMIT_SHA: ${CI_COMMIT_SHA}

    ports:
      - "8081:80"

  frontend-viewer:
    image: ghcr.io/tart-telescope/web_app/viewer-subpath:${CI_COMMIT_SHA}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_PROJECT_NAME: viewer
        BASE_URL: "/viewer"
        CI_COMMIT_SHA: ${CI_COMMIT_SHA}
    ports:
      - "8082:80"
