version: '3.8'

services:
    frontend:
        image: ghcr.io/tmolteno/tart/frontend:latest
        build:
          context: .
          dockerfile: Dockerfile
          args:
            CI_PROJECT_NAME: viewer  # needed if exposed as /viewer
        ports:
          - '8080:80'

networks:
    default:
        enable_ipv6: false
