services:
  frontend:
    image: ghcr.io/tart-telescope/web_app/viewer:${CI_COMMIT_SHA}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CI_PROJECT_NAME: viewer # needed if exposed as /viewer
        BASE_URL: ${BASE_URL}
        CI_COMMIT_SHA: ${CI_COMMIT_SHA} # CI_COMMIT_SHA short bash: export CI_COMMIT_SHA=$(git rev-parse --short HEAD)

    ports:
      - "8080:80"

networks:
  default:
    enable_ipv6: false
