name: Cleanup Build Cache

on:
  schedule:
    # Run every week on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
    - name: Cleanup old caches
      uses: actions/github-script@v7
      with:
        script: |
          const caches = await github.rest.actions.getActionsCaches({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });

          // Keep caches from the last 7 days
          const cutoffDate = new Date();
          cutoffDate.setDate(cutoffDate.getDate() - 7);

          let deletedCount = 0;
          let totalSize = 0;

          for (const cache of caches.data.actions_caches) {
            const cacheDate = new Date(cache.created_at);
            
            if (cacheDate < cutoffDate) {
              console.log(`Deleting cache: ${cache.key} (${cache.size_in_bytes} bytes, created: ${cache.created_at})`);
              
              try {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id
                });
                deletedCount++;
                totalSize += cache.size_in_bytes;
              } catch (error) {
                console.log(`Failed to delete cache ${cache.key}: ${error.message}`);
              }
            }
          }

          console.log(`\nCleanup completed:`);
          console.log(`- Deleted ${deletedCount} caches`);
          console.log(`- Freed ${(totalSize / (1024 * 1024)).toFixed(2)} MB`);